services:
  web-proxy:
    ports:
      - 8999:80

  wis2box-ui:
    ports:
      - 9999:80

  minio:
    ports:
      - "9000:9000"
      - "9001:9001"
    deploy:
      replicas: 1

  mosquitto:
    ports:
      - 1883:1883
      - 8884:8884

  frost-sta:
    ports:
      - 8080:8080

  frost-mqtt:
    ports:
      - 9876:9876
