services:
  web-proxy:
    container_name: nginx
    image: nginx:alpine
    restart: always
    env_file:
      - default.env
      - ../dev.env
    depends_on:
      - wis2box-ui
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  wis2box-ui:
    container_name: wis2box-ui
    image: ghcr.io/cgs-earth/hub2box-ui:latest
    env_file:
      - default.env
      - ../dev.env
    depends_on:
      - wis2box-api

  wis2box-api:
    container_name: wis2box-api
    image: ghcr.io/cgs-earth/hub2box-api:latest
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - api-config:/data/wis2box/config/pygeoapi/:rw
    depends_on:
      frost-sta:
        condition: service_started

  minio:
    container_name: wis2box-minio
    image: minio/minio
    mem_limit: 512m
    memswap_limit: 512m
    restart: always
    env_file:
      - default.env
      - ../dev.env
    command: server --console-address ":9001" /data
    # in a production-setup minio needs to be
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 1s
      retries: 3
    depends_on:
      mosquitto:
        condition: service_started

  mosquitto:
    container_name: mosquitto
    #image: ghcr.io/wmo-im/wis2box-broker:latest
    build:
      context: ./mosquitto
    env_file:
      - default.env
      - ../dev.env

  wis2box:
    container_name: wis2box
    mem_limit: 1g
    memswap_limit: 1g
    restart: always
    #image: ghcr.io/wmo-im/wis2box:0.5.1
    build:
      context: ..
      # args:
      #   WIS2BOX_PIP3_EXTRA_PACKAGES: ${WIS2BOX_PIP3_EXTRA_PACKAGES}
    #user: wis2box:wis2box
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}:/data/wis2box:rw
    depends_on:
      minio:
        condition: service_healthy
      mosquitto:
        condition: service_started
      wis2box-api:
        condition: service_started
    command: ["wis2box", "pubsub" , "subscribe", "--broker", "http://wis2box-minio:9000", "--topic", "wis2box-storage/#"]

  wis2box-auth:
    container_name: wis2box-auth
    image: ghcr.io/wmo-im/wis2box-auth:latest
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - auth-data:/data/wis2box:rw
    depends_on:
      - wis2box

  frost-sta:
    container_name: frost-sta
    image: fraunhoferiosb/frost-server-http:2.0
    env_file:
      - default.env
      - ../dev.env
    environment:
      - queueLoggingInterval=1000
      - plugins.multiDatastream.enable=true
      - http_cors_enable=true
      - http_cors_allowed_origins=*
      - bus_mqttBroker=tcp://mosquitto:1883
      - bus_sendQueueSize=2000
      - bus_sendWorkerPoolSize=10
      - bus_maxInFlight=2000
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
      - persistence_idGenerationMode=ServerAndClientGenerated
      - persistence_autoUpdateDatabase=true
    depends_on:
      - database
      - mosquitto

  frost-mqtt:
    container_name: frost-mqtt
    image: fraunhoferiosb/frost-server-mqtt:2.0
    env_file:
      - default.env
      - ../dev.env
    environment:
      - queueLoggingInterval=1000
      - plugins.multiDatastream.enable=true
      - bus_busImplementationClass=de.fraunhofer.iosb.ilt.sta.messagebus.MqttMessageBus
      - mqtt_CreateThreadPoolSize=10
      - mqtt_CreateMessageQueueSize=10000
      - mqtt_SubscribeThreadPoolSize=20
      - mqtt_SubscribeMessageQueueSize=10000
      - persistence_persistenceManagerImplementationClass=de.fraunhofer.iosb.ilt.sta.persistence.postgres.PostgresPersistenceManager
      - persistence_db_driver=org.postgresql.Driver
      - persistence_db_url=jdbc:postgresql://database:5432/sensorthings
      - persistence_db_username=sensorthings
      - persistence_db_password=ChangeMe
    depends_on:
      - database
      - mosquitto

  database:
    container_name: database
    image: postgis/postgis:14-3.2-alpine
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    volumes:
      - postgis_volume:/var/lib/postgresql/data

volumes:
  minio-data:
  auth-data:
  api-config:
  postgis_volume:
