services:
  web-proxy:
    container_name: nginx
    image: nginx:alpine
    restart: always
    env_file:
      - default.env
      - ../dev.env
    depends_on:
      - wis2box-ui
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

  wis2box-ui:
    container_name: wis2box-ui
    image: internetofwater/hub2box-ui:wqx
    env_file:
      - default.env
      - ../dev.env
      - sta.env
    depends_on:
      - wis2box-api

  wis2box-api:
    container_name: wis2box-api
    image: internetofwater/hub2box-api:wqx
    restart: always
    env_file:
      - default.env
      - ../dev.env
      - sta.env
    volumes:
      - api-config:/data/wis2box/config/pygeoapi/:rw
    depends_on:
      frost-http:
        condition: service_started

  minio:
    container_name: wis2box-minio
    image: minio/minio:RELEASE.2022-12-02T19-19-22Z.fips
    mem_limit: 512m
    memswap_limit: 512m
    restart: always
    env_file:
      - default.env
      - ../dev.env
    command: server --console-address ":9001" /data
    # in a production-setup minio needs to be
    volumes:
      - minio-data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 5s
      timeout: 1s
      retries: 3
    depends_on:
      mosquitto:
        condition: service_started

  mosquitto:
    container_name: mosquitto
    #image: ghcr.io/wmo-im/wis2box-broker:latest
    build:
      context: ./mosquitto
    env_file:
      - default.env
      - ../dev.env

  wis2box:
    container_name: wis2box
    mem_limit: 1g
    memswap_limit: 1g
    restart: always
    #image: ghcr.io/wmo-im/wis2box:0.5.1
    build:
      context: ..
      # args:
      #   WIS2BOX_PIP3_EXTRA_PACKAGES: ${WIS2BOX_PIP3_EXTRA_PACKAGES}
    #user: wis2box:wis2box
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - ${WIS2BOX_HOST_DATADIR}:/data/wis2box:rw
    depends_on:
      minio:
        condition: service_healthy
      mosquitto:
        condition: service_started
      wis2box-api:
        condition: service_started
    command: ["wis2box", "pubsub" , "subscribe", "--broker", "http://wis2box-minio:9000", "--topic", "wis2box-storage/#"]

  wis2box-auth:
    container_name: wis2box-auth
    image: ghcr.io/wmo-im/wis2box-auth:0.5.1
    env_file:
      - default.env
      - ../dev.env
    volumes:
      - auth-data:/data/wis2box:rw
    depends_on:
      - wis2box

  frost-http:
    container_name: frost-http
    image: hylkevds/frost-http-waterquality:latest
    env_file:
      - default.env
      - ../dev.env
      - sta.env
    depends_on:
      - database
      - mosquitto
    platform: linux/amd64

  frost-mqtt:
    container_name: frost-mqtt
    image: fraunhoferiosb/frost-server-mqtt:2.2.0-SNAPSHOT
    env_file:
      - default.env
      - ../dev.env
      - sta.env
    depends_on:
      - database
      - mosquitto

  database:
    container_name: database
    build:
      context: ./database
    env_file:
      - default.env
      - sta.env
    volumes:
      - postgis_volume:/var/lib/postgresql/data

volumes:
  minio-data:
  auth-data:
  api-config:
  postgis_volume:
